markdown: rdiscount 
permalink: /:title 
title: DosLin's Blog
url: http://doslin.com
subscribe: http://doslin.com/feed.xml
exclude: [ README.md, newpost.rb ]
domain: doslin.com
author: DosLin
email: root@ijava.me
auto: true
twitterID: javachord
googleAnalyticsID: UA-40430247-1
disqusShortname: doslin
paginate: 12
